server:
  ip_backend: "0.0.0.0"
  ip_frontend: "127.0.0.1"
  port: 9123
  secret: "your_secret_token_here"
  user: "admin"
  password: "admin123"

path:
  generated: "generated"
  playbooks: "playbooks"
  logs: "logs"
